version: '3.8'

services:
  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - wing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Admin App (Next.js/Shadcn)
  admin-app:
    build:
      context: ../client/admin
      dockerfile: Dockerfile
    container_name: admin-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - wing-network
    volumes:
      - ./logs:/app/logs
    depends_on:
      - dashboard-service
      - auth-service
      - marketing-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Dashboard Service
  dashboard-service:
    build:
      context: .
      dockerfile: apps/services/dashboard-service/Dockerfile
    container_name: dashboard-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5001
    restart: unless-stopped
    networks:
      - wing-network
    volumes:
      - ./logs:/app/logs
      - ../data:/app/data:ro
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: apps/services/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5002
    restart: unless-stopped
    networks:
      - wing-network
    volumes:
      - ./logs:/app/logs
      - ../data:/app/data:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Marketing Service
  marketing-service:
    build:
      context: .
      dockerfile: apps/services/marketing-service/Dockerfile
    container_name: marketing-service
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5003
    restart: unless-stopped
    networks:
      - wing-network
    volumes:
      - ./logs:/app/logs
      - ../data:/app/data:ro
    depends_on:
      - dashboard-service
      - ollama
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local

networks:
  wing-network:
    driver: bridge 